Server:
  http:
    port: 8085
    read_timeout: "5s"
    write_timeout: "5s"
    idle_timeout: "120s"
  grpc:
    port: 8086
  environment: "development"

logging:
  level: "info"
  format: "json"

cache:
  type: "redis"
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT}"
